app:
  name: Tallink Test Task
  description: "Tallink Test Task"
  version: "0.0.1"

api:
  version: v1
  prefix: /api/public

java:
  version: 1.8

spring:
  main.banner-mode: "off"
  application.name: ${app.name}
  output.ansi.enabled: always
  datasource:
    url: jdbc:h2:mem:app_db;DB_CLOSE_ON_EXIT=FALSE
    username: tallink
    password: tallink
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081
  use-forward-headers: true
  compression:
    enabled: true
    min-response-size: 8192
    mime-types:
      - application/json
      - text/html
      - text/css
      - application/javascript

management.security.enabled: false

